"""Build the pre-specification record Reviewer 3 asked for (R3.1).

Reviewer 3: "Provide the preregistration record or timestamp supporting the claim
that all four hypotheses were fixed before analysis."

The honest answer is partly yes and partly no, and this script derives it from
git rather than from memory:

  * H01-H03 appear in the repository on 9 Feb 2026, in the README hypothesis
    table, plans/aims-and-challenges.md and the original research proposal PDF --
    before the first prototype run.
  * H04 appears only in August 2026, AFTER retrieval experiments had been run. It
    is therefore NOT pre-specified, and the paper must stop implying that it is.
  * The analysis plan also changed: the planned H02 test was "Two-way ANOVA /
    Kruskal-Wallis", and the paper reports per-arm correlations instead.

This is not a registry entry. A git commit is a timestamp the reviewer can click,
which is better than nothing and weaker than OSF; the output says so plainly.

No API calls. Reads git history.
Writes results/prespecification_record.md.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

OUT = Path("results/prespecification_record.md")
REPO_URL = "https://github.com/saaachis/hinglish-grounded-medical-rag"

#: The commit that first contains the hypothesis table, plans and proposal PDF.
SPEC_COMMIT = "0917322"
#: Files in that commit that state the hypotheses.
SPEC_FILES = ["README.md", "plans/aims-and-challenges.md", "plans/timeline.md",
              "research-work/group 5 - research proposal.pdf"]


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], capture_output=True, text=True,
                              check=True, encoding="utf-8", errors="replace").stdout.strip()
    except Exception as e:                        # a shallow clone or no git: degrade, don't crash
        logger.warning("git %s failed: %s", " ".join(args), e)
        return ""


def commit_date(ref: str) -> str:
    return git("log", "-1", "--format=%ad", "--date=iso", ref)


def first_commit_touching(pattern: str) -> tuple[str, str, str]:
    """Earliest commit whose diff introduces `pattern`, as (hash, date, subject)."""
    out = git("log", "--reverse", "--format=%h|%ad|%s", "--date=short", "-S", pattern)
    if not out:
        return ("", "", "")
    return tuple(out.splitlines()[0].split("|", 2))  # type: ignore[return-value]


def main() -> None:
    spec_date = commit_date(SPEC_COMMIT)
    first_prototype = git("log", "--reverse", "--format=%h|%ad|%s", "--date=short",
                          "--grep=prototype", "-i")
    proto = first_prototype.splitlines()[0].split("|", 2) if first_prototype else ["", "", ""]

    h4 = first_commit_touching("H04")
    h4_alt = first_commit_touching("H₀₄")
    h4_best = h4 if h4[0] else h4_alt

    present = []
    for f in SPEC_FILES:
        blob = git("show", f"{SPEC_COMMIT}:{f}")
        hits = []
        if blob:
            for h in ("H1", "H2", "H3", "H01", "H02", "H03"):
                if re.search(rf"\b{h}\b", blob):
                    hits.append(h)
        present.append((f, sorted(set(hits)) or (["(binary file)"] if not blob else [])))

    L = ["# Pre-specification record", "",
         "Generated by `python -m src.analysis.prespecification_record` from git history.", "",
         "## What was fixed, and when", "",
         "| Hypothesis | First in the repository | Before any analysis? |",
         "|---|---|---|",
         f"| H01 grounding effect | `{SPEC_COMMIT}`, {spec_date} | **Yes** |",
         f"| H02 code-mixing robustness | `{SPEC_COMMIT}`, {spec_date} | **Yes** |",
         f"| H03 evidence provenance | `{SPEC_COMMIT}`, {spec_date} | **Yes** |",
         (f"| H04 retrieval penalty | `{h4_best[0]}`, {h4_best[1]} | **No** — added after the "
          "retrieval experiments |") if h4_best[0] else
         "| H04 retrieval penalty | not found in git history | **No** |",
         "",
         f"First prototype run: `{proto[0]}`, {proto[1]} ({proto[2]})." if proto[0] else "",
         "",
         f"Clickable timestamp: {REPO_URL}/commit/{SPEC_COMMIT}", "",
         "### Where the hypotheses are stated in that commit", "",
         "| File | Hypotheses named |", "|---|---|"]
    for f, hits in present:
        L.append(f"| `{f}` | {', '.join(hits) if hits else '—'} |")

    L += ["", "## What the paper must say instead of \"pre-registered\"", "",
          "This is a timestamped public commit, not a registry entry (OSF, AsPredicted).",
          "Use **pre-specified**, and disclose the two deviations below.", "",
          "> H01-H03 were specified in the project proposal and repository before any data were",
          f"> analysed ({SPEC_COMMIT}, {spec_date[:10]}); the first prototype run followed on",
          f"> {proto[1] or 'a later date'}. H04 was formulated after the initial retrieval",
          "> experiments and is reported as a post-hoc hypothesis, tested confirmatorily on the",
          "> full matched set. Deviations from the original analysis plan are listed in Sect. X.",
          "",
          "## Deviations from the pre-specified analysis plan", "",
          "| # | Planned | Reported | Why |",
          "|---|---|---|---|",
          "| 1 | H02 by \"Two-way ANOVA / Kruskal-Wallis\" on code-mixing level | per-arm Spearman "
          "correlations | The planned interaction test is now reported as primary "
          "(`h2_prespecified_test.md`); the per-arm analysis is labelled exploratory |",
          "| 2 | factual consistency and hallucination rate as two outcomes | factual support only |"
          " `hallucination` is exactly `1 - precision`, so reporting both double-counts one result |",
          "| 3 | concept precision as the quality metric | F1 reported wherever quality is at issue |"
          " degenerate baselines showed precision's optimum is a one-word answer |",
          "| 4 | Code-Mixing Index over a fixed Hindi word list | repaired Hindi-proportion measure |"
          " the original list counted \"doctor\" and \"please\" as Hindi (71.0% and 38.0% of queries) |",
          "| 5 | H03 on answer quality | reported as exploratory; refusal as a secondary outcome |"
          " only 13 of 160 queries were jointly scoreable (`h3_power.md`) |",
          ""]
    OUT.write_text("\n".join(l for l in L if l is not None), encoding="utf-8")
    print(OUT.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
